### ISSUE TITLE
Can you replace MaterialIcons with MaterialCommunityIcons?

### ISSUE THREAD

**Issue by xvonabur** [xotahal/react-native-material-ui#194]
Hi!

I need to use some icons from MaterialCommunityIcons in my project. Can you replace `import VectorIcon from 'react-native-vector-icons/MaterialIcons';` with `import VectorIcon from 'react-native-vector-icons/MaterialCommunityIcons';` in `Icon\index.js` file?

Unfortunately, I haven't tested yet, whether it's breaking test or not, so I'm asking you. Can you suggest another way to replace icons? Of course I can fork this project, but my resources is limited and I don't want to maintain it.

**Comment by xotahal** [comment]
Hey :)

> but my resources is limited and I don't want to maintain it

Like that :) Gonna try to use it when my girlfriend says to me I don't have enough resources for her :D 

Anyway, I think you can still use whatever you want. Just import it to your project and send Icon to our components. I'm not about to change it right now. Because we need to remove react-native-vector-icons completely. Then we need to import icons directly.

**Comment by xvonabur** [comment]
> Just import it to your project and send Icon to our components.

I'm already doing that. So, no alternatives by now. Thanks, anyway.


> Because we need to remove react-native-vector-icons completely. 

I didn't know that. Make sense, through.

> Gonna try to use it when my girlfriend says to me I don't have enough resources for her :D

Nice catch :D

Anyway, I rather help you with this project, than maintain my own fork.
