### ISSUE TITLE
Ripple not showing on iOS?

### ISSUE THREAD

**Issue by FezVrasta** [xotahal/react-native-material-ui#234]
The ripple effect doesn't show at all on iOS, how can I fix it?

**Comment by xotahal** [comment]
It's fixed in latest version. Isn't it? You can read about it on my
medium.com/@xotahal account 😉

**Comment by FezVrasta** [comment]
I updated and now the ripple appears only onPressOut, which is different from Android.

Is this expected?

**Comment by FezVrasta** [comment]
Also, I'm getting this warning now with the latest version:
![image](https://user-images.githubusercontent.com/5382443/33484010-da30e1a8-d6a0-11e7-87b4-c104c4c59612.png)

**Comment by FezVrasta** [comment]
I'm also getting this now :-(

![image](https://user-images.githubusercontent.com/5382443/33485994-bee6f90c-d6a8-11e7-9460-15bee5d24550.png)

**Comment by xotahal** [comment]
Warnings are fixed and will be released in next version.

About ripple effect. Please read this article - https://medium.com/react-native-motion/ios-ripple-effect-in-react-native-30ee97a5aa8c

It happens in onPressOut only if you use onLongPress. Otherwise everything happens in onPress. It's the same like on android.

**Comment by FezVrasta** [comment]
The problem is that the animation doesn't happen on `onPress`, but `onPressOut`
