### ISSUE TITLE
Badge on icons?

### ISSUE THREAD

**Issue by jpsantos7** [xotahal/react-native-material-ui#35]
Will there be support for the badge on the icons like we can see in the images on the readme?
![](https://raw.githubusercontent.com/react-native-material-design/demo-app/master/resources/examples-1.jpg)

This comes pretty handy for shopping cart items, or chat notifications, etc.

**Comment by xotahal** [comment]
Hi @jpsantos7,

I removed them for some reason, sorry for that. But we need them as well now (for notifications, how you said). So I'm gonna put them back ;)

**Comment by xotahal** [comment]
Hey @jpsantos7,

I've just started to implement that badge component. And we could discuss how it should be done.

This is what I have so far: (there is a bug with raised button - zIndex)
<img width="217" alt="screen shot 2016-11-05 at 12 33 24 pm" src="https://cloud.githubusercontent.com/assets/3531955/20029702/17b5d1fe-a354-11e6-923d-2a4c4ca6b598.png">

There should be ability to: 
- add badge to any React element
- set `top` and `left` (due to position of badge)
- set `width`, `height` and `borderRadius`  - cause there is no `borderRadius: 50%` in React native
- specify content of badge (React element or string, where string is just sugar for `<Text>3</Text>`)

Anything else? What do you mean?

**Comment by jpsantos7** [comment]
That's great @xotahal !
I think that maybe the badge position should also be configurable for any combo (top+left, bottom+right, etc.)
It would also be great to be able to set an icon on the notification.
I say this because it may be used for something like what's on the following image (the first example):
![notifications_anatomy_02_comparison](https://cloud.githubusercontent.com/assets/1482804/20032765/7d719d2c-a389-11e6-8fc3-551ecee930ba.png)
I realize we are able to do this with a React element but it still would be really cool to just set `icon="star"` for example.

just my 2 cent ;)

**Comment by xotahal** [comment]
OK, great points @jpsantos7 - thank you ;) Hope I'll manage it all till end of this week ...

**Comment by xotahal** [comment]
Well, It's done ;)

<img width="284" alt="screen shot 2016-11-15 at 1 47 26 pm" src="https://cloud.githubusercontent.com/assets/3531955/20306355/152f485a-ab3a-11e6-9af2-00994fed4785.png">

I need to fix some breaking layout changes in RN0.36 and gonna publish new version ;)

**Comment by hakunin** [comment]
Can't wait to play with this project once I get some basic stuff down in RN :)

**Comment by xotahal** [comment]
Published - https://github.com/xotahal/react-native-material-ui/releases/tag/v1.4.0
