### ISSUE TITLE
Documentation for Card and Drawer components

### ISSUE THREAD

**Issue by vtisnado** [xotahal/react-native-material-ui#82]
Hi @xotahal could you add a brief example in how to use the **Card** and **Drawer** components? I think both are the most common ones. Also if you can add something about the **List item** will be great!

Nice work with this repo, thanks a lot for your contribution.

**Comment by HofmannZ** [comment]
Hey @vtisnado,

I believe @xotahal is somewhat bussy since he only checks for PRs on a week or so, but hey, it's open source. If you're looking for a working example you can take a look at the [demo app](https://github.com/xotahal/react-native-material-ui-demo-app). I use it to test the new components before I PR them, but I think you can just as well use them to figure out how the components work.

Good luck!

**Comment by vtisnado** [comment]
Thanks for your soon answer @HofmannZ I will check the demo app, don't know why I didn't see it before.
